# Generated by Django 2.0.4 on 2018-12-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181217_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group_name',
            field=models.TextField(max_length=150),
        ),
    ]
